language: python
python:
    - "2.7"
install:
    - "pip install pep8 nose mock httplib2 lettuce pyral requests"
script:
    - "pep8 bin/github-to-rally"
    - "nosetests -vv test/"
notifications:
    email: false
